export enum KnownColor {
    Transparent = 28,
    AliceBlue = 29,
    AntiqueWhite = 30,
    Aqua = 31,
    Aquamarine = 32,
    Azure = 33,
    Beige = 34,
    Bisque = 35,
    Black = 36,
    BlanchedAlmond = 37,
    Blue = 38,
    BlueViolet = 39,
    Brown = 40,
    BurlyWood = 41,
    CadetBlue = 42,
    Chartreuse = 43,
    Chocolate = 44,
    Coral = 45,
    CornflowerBlue = 46,
    Cornsilk = 47,
    Crimson = 48,
    Cyan = 49,
    DarkBlue = 50,
    DarkCyan = 51,
    DarkGoldenrod = 52,
    DarkGray = 53,
    DarkGreen = 54,
    DarkKhaki = 55,
    DarkMagenta = 56,
    DarkOliveGreen = 57,
    DarkOrange = 58,
    DarkOrchid = 59,
    DarkRed = 60,
    DarkSalmon = 61,
    DarkSeaGreen = 62,
    DarkSlateBlue = 63,
    DarkSlateGray = 64,
    DarkTurquoise = 65,
    DarkViolet = 66,
    DeepPink = 67,
    DeepSkyBlue = 68,
    DimGray = 69,
    DodgerBlue = 70,
    Firebrick = 71,
    FloralWhite = 72,
    ForestGreen = 73,
    Fuchsia = 74,
    Gainsboro = 75,
    GhostWhite = 76,
    Gold = 77,
    Goldenrod = 78,
    Gray = 79,
    Green = 80,
    GreenYellow = 81,
    Honeydew = 82,
    HotPink = 83,
    IndianRed = 84,
    Indigo = 85,
    Ivory = 86,
    Khaki = 87,
    Lavender = 88,
    LavenderBlush = 89,
    LawnGreen = 90,
    LemonChiffon = 91,
    LightBlue = 92,
    LightCoral = 93,
    LightCyan = 94,
    LightGoldenrodYellow = 95,
    LightGray = 96,
    LightGreen = 97,
    LightPink = 98,
    LightSalmon = 99,
    LightSeaGreen = 100,
    LightSkyBlue = 101,
    LightSlateGray = 102,
    LightSteelBlue = 103,
    LightYellow = 104,
    Lime = 105,
    LimeGreen = 106,
    Linen = 107,
    Magenta = 108,
    Maroon = 109,
    MediumAquamarine = 110,
    MediumBlue = 111,
    MediumOrchid = 112,
    MediumPurple = 113,
    MediumSeaGreen = 114,
    MediumSlateBlue = 115,
    MediumSpringGreen = 116,
    MediumTurquoise = 117,
    MediumVioletRed = 118,
    MidnightBlue = 119,
    MintCream = 120,
    MistyRose = 121,
    Moccasin = 122,
    NavajoWhite = 123,
    Navy = 124,
    OldLace = 125,
    Olive = 126,
    OliveDrab = 127,
    Orange = 128,
    OrangeRed = 129,
    Orchid = 130,
    PaleGoldenrod = 131,
    PaleGreen = 132,
    PaleTurquoise = 133,
    PaleVioletRed = 134,
    PapayaWhip = 135,
    PeachPuff = 136,
    Peru = 137,
    Pink = 138,
    Plum = 139,
    PowderBlue = 140,
    Purple = 141,
    Red = 142,
    RosyBrown = 143,
    RoyalBlue = 144,
    SaddleBrown = 145,
    Salmon = 146,
    SandyBrown = 147,
    SeaGreen = 148,
    SeaShell = 149,
    Sienna = 150,
    Silver = 151,
    SkyBlue = 152,
    SlateBlue = 153,
    SlateGray = 154,
    Snow = 155,
    SpringGreen = 156,
    SteelBlue = 157,
    Tan = 158,
    Teal = 159,
    Thistle = 160,
    Tomato = 161,
    Turquoise = 162,
    Violet = 163,
    Wheat = 164,
    White = 165,
    WhiteSmoke = 166,
    Yellow = 167,
    YellowGreen = 168,
    RebeccaPurple = 169,
}

export const KNOWN_COLOR_NAMES: Record<KnownColor, string> = {
    [KnownColor.Transparent]: 'Transparent',
    [KnownColor.AliceBlue]: 'AliceBlue',
    [KnownColor.AntiqueWhite]: 'AntiqueWhite',
    [KnownColor.Aqua]: 'Aqua',
    [KnownColor.Aquamarine]: 'Aquamarine',
    [KnownColor.Azure]: 'Azure',
    [KnownColor.Beige]: 'Beige',
    [KnownColor.Bisque]: 'Bisque',
    [KnownColor.Black]: 'Black',
    [KnownColor.BlanchedAlmond]: 'BlanchedAlmond',
    [KnownColor.Blue]: 'Blue',
    [KnownColor.BlueViolet]: 'BlueViolet',
    [KnownColor.Brown]: 'Brown',
    [KnownColor.BurlyWood]: 'BurlyWood',
    [KnownColor.CadetBlue]: 'CadetBlue',
    [KnownColor.Chartreuse]: 'Chartreuse',
    [KnownColor.Chocolate]: 'Chocolate',
    [KnownColor.Coral]: 'Coral',
    [KnownColor.CornflowerBlue]: 'CornflowerBlue',
    [KnownColor.Cornsilk]: 'Cornsilk',
    [KnownColor.Crimson]: 'Crimson',
    [KnownColor.Cyan]: 'Cyan',
    [KnownColor.DarkBlue]: 'DarkBlue',
    [KnownColor.DarkCyan]: 'DarkCyan',
    [KnownColor.DarkGoldenrod]: 'DarkGoldenrod',
    [KnownColor.DarkGray]: 'DarkGray',
    [KnownColor.DarkGreen]: 'DarkGreen',
    [KnownColor.DarkKhaki]: 'DarkKhaki',
    [KnownColor.DarkMagenta]: 'DarkMagenta',
    [KnownColor.DarkOliveGreen]: 'DarkOliveGreen',
    [KnownColor.DarkOrange]: 'DarkOrange',
    [KnownColor.DarkOrchid]: 'DarkOrchid',
    [KnownColor.DarkRed]: 'DarkRed',
    [KnownColor.DarkSalmon]: 'DarkSalmon',
    [KnownColor.DarkSeaGreen]: 'DarkSeaGreen',
    [KnownColor.DarkSlateBlue]: 'DarkSlateBlue',
    [KnownColor.DarkSlateGray]: 'DarkSlateGray',
    [KnownColor.DarkTurquoise]: 'DarkTurquoise',
    [KnownColor.DarkViolet]: 'DarkViolet',
    [KnownColor.DeepPink]: 'DeepPink',
    [KnownColor.DeepSkyBlue]: 'DeepSkyBlue',
    [KnownColor.DimGray]: 'DimGray',
    [KnownColor.DodgerBlue]: 'DodgerBlue',
    [KnownColor.Firebrick]: 'Firebrick',
    [KnownColor.FloralWhite]: 'FloralWhite',
    [KnownColor.ForestGreen]: 'ForestGreen',
    [KnownColor.Fuchsia]: 'Fuchsia',
    [KnownColor.Gainsboro]: 'Gainsboro',
    [KnownColor.GhostWhite]: 'GhostWhite',
    [KnownColor.Gold]: 'Gold',
    [KnownColor.Goldenrod]: 'Goldenrod',
    [KnownColor.Gray]: 'Gray',
    [KnownColor.Green]: 'Green',
    [KnownColor.GreenYellow]: 'GreenYellow',
    [KnownColor.Honeydew]: 'Honeydew',
    [KnownColor.HotPink]: 'HotPink',
    [KnownColor.IndianRed]: 'IndianRed',
    [KnownColor.Indigo]: 'Indigo',
    [KnownColor.Ivory]: 'Ivory',
    [KnownColor.Khaki]: 'Khaki',
    [KnownColor.Lavender]: 'Lavender',
    [KnownColor.LavenderBlush]: 'LavenderBlush',
    [KnownColor.LawnGreen]: 'LawnGreen',
    [KnownColor.LemonChiffon]: 'LemonChiffon',
    [KnownColor.LightBlue]: 'LightBlue',
    [KnownColor.LightCoral]: 'LightCoral',
    [KnownColor.LightCyan]: 'LightCyan',
    [KnownColor.LightGoldenrodYellow]: 'LightGoldenrodYellow',
    [KnownColor.LightGray]: 'LightGray',
    [KnownColor.LightGreen]: 'LightGreen',
    [KnownColor.LightPink]: 'LightPink',
    [KnownColor.LightSalmon]: 'LightSalmon',
    [KnownColor.LightSeaGreen]: 'LightSeaGreen',
    [KnownColor.LightSkyBlue]: 'LightSkyBlue',
    [KnownColor.LightSlateGray]: 'LightSlateGray',
    [KnownColor.LightSteelBlue]: 'LightSteelBlue',
    [KnownColor.LightYellow]: 'LightYellow',
    [KnownColor.Lime]: 'Lime',
    [KnownColor.LimeGreen]: 'LimeGreen',
    [KnownColor.Linen]: 'Linen',
    [KnownColor.Magenta]: 'Magenta',
    [KnownColor.Maroon]: 'Maroon',
    [KnownColor.MediumAquamarine]: 'MediumAquamarine',
    [KnownColor.MediumBlue]: 'MediumBlue',
    [KnownColor.MediumOrchid]: 'MediumOrchid',
    [KnownColor.MediumPurple]: 'MediumPurple',
    [KnownColor.MediumSeaGreen]: 'MediumSeaGreen',
    [KnownColor.MediumSlateBlue]: 'MediumSlateBlue',
    [KnownColor.MediumSpringGreen]: 'MediumSpringGreen',
    [KnownColor.MediumTurquoise]: 'MediumTurquoise',
    [KnownColor.MediumVioletRed]: 'MediumVioletRed',
    [KnownColor.MidnightBlue]: 'MidnightBlue',
    [KnownColor.MintCream]: 'MintCream',
    [KnownColor.MistyRose]: 'MistyRose',
    [KnownColor.Moccasin]: 'Moccasin',
    [KnownColor.NavajoWhite]: 'NavajoWhite',
    [KnownColor.Navy]: 'Navy',
    [KnownColor.OldLace]: 'OldLace',
    [KnownColor.Olive]: 'Olive',
    [KnownColor.OliveDrab]: 'OliveDrab',
    [KnownColor.Orange]: 'Orange',
    [KnownColor.OrangeRed]: 'OrangeRed',
    [KnownColor.Orchid]: 'Orchid',
    [KnownColor.PaleGoldenrod]: 'PaleGoldenrod',
    [KnownColor.PaleGreen]: 'PaleGreen',
    [KnownColor.PaleTurquoise]: 'PaleTurquoise',
    [KnownColor.PaleVioletRed]: 'PaleVioletRed',
    [KnownColor.PapayaWhip]: 'PapayaWhip',
    [KnownColor.PeachPuff]: 'PeachPuff',
    [KnownColor.Peru]: 'Peru',
    [KnownColor.Pink]: 'Pink',
    [KnownColor.Plum]: 'Plum',
    [KnownColor.PowderBlue]: 'PowderBlue',
    [KnownColor.Purple]: 'Purple',
    [KnownColor.Red]: 'Red',
    [KnownColor.RosyBrown]: 'RosyBrown',
    [KnownColor.RoyalBlue]: 'RoyalBlue',
    [KnownColor.SaddleBrown]: 'SaddleBrown',
    [KnownColor.Salmon]: 'Salmon',
    [KnownColor.SandyBrown]: 'SandyBrown',
    [KnownColor.SeaGreen]: 'SeaGreen',
    [KnownColor.SeaShell]: 'SeaShell',
    [KnownColor.Sienna]: 'Sienna',
    [KnownColor.Silver]: 'Silver',
    [KnownColor.SkyBlue]: 'SkyBlue',
    [KnownColor.SlateBlue]: 'SlateBlue',
    [KnownColor.SlateGray]: 'SlateGray',
    [KnownColor.Snow]: 'Snow',
    [KnownColor.SpringGreen]: 'SpringGreen',
    [KnownColor.SteelBlue]: 'SteelBlue',
    [KnownColor.Tan]: 'Tan',
    [KnownColor.Teal]: 'Teal',
    [KnownColor.Thistle]: 'Thistle',
    [KnownColor.Tomato]: 'Tomato',
    [KnownColor.Turquoise]: 'Turquoise',
    [KnownColor.Violet]: 'Violet',
    [KnownColor.Wheat]: 'Wheat',
    [KnownColor.White]: 'White',
    [KnownColor.WhiteSmoke]: 'WhiteSmoke',
    [KnownColor.Yellow]: 'Yellow',
    [KnownColor.YellowGreen]: 'YellowGreen',
    [KnownColor.RebeccaPurple]: 'RebeccaPurple',
};
