import { KnownColor } from './known_color.js';

const COLOR_VALUE_TABLE: Record<KnownColor, number> = {
    [KnownColor.Transparent]: 0x00ffffff,
    [KnownColor.AliceBlue]: 0xfff0f8ff,
    [KnownColor.AntiqueWhite]: 0xfffaebd7,
    [KnownColor.Aqua]: 0xff00ffff,
    [KnownColor.Aquamarine]: 0xff7fffd4,
    [KnownColor.Azure]: 0xfff0ffff,
    [KnownColor.Beige]: 0xfff5f5dc,
    [KnownColor.Bisque]: 0xffffe4c4,
    [KnownColor.Black]: 0xff000000,
    [KnownColor.BlanchedAlmond]: 0xffffebcd,
    [KnownColor.Blue]: 0xff0000ff,
    [KnownColor.BlueViolet]: 0xff8a2be2,
    [KnownColor.Brown]: 0xffa52a2a,
    [KnownColor.BurlyWood]: 0xffdeb887,
    [KnownColor.CadetBlue]: 0xff5f9ea0,
    [KnownColor.Chartreuse]: 0xff7fff00,
    [KnownColor.Chocolate]: 0xffd2691e,
    [KnownColor.Coral]: 0xffff7f50,
    [KnownColor.CornflowerBlue]: 0xff6495ed,
    [KnownColor.Cornsilk]: 0xfffff8dc,
    [KnownColor.Crimson]: 0xffdc143c,
    [KnownColor.Cyan]: 0xff00ffff,
    [KnownColor.DarkBlue]: 0xff00008b,
    [KnownColor.DarkCyan]: 0xff008b8b,
    [KnownColor.DarkGoldenrod]: 0xffb8860b,
    [KnownColor.DarkGray]: 0xffa9a9a9,
    [KnownColor.DarkGreen]: 0xff006400,
    [KnownColor.DarkKhaki]: 0xffbdb76b,
    [KnownColor.DarkMagenta]: 0xff8b008b,
    [KnownColor.DarkOliveGreen]: 0xff556b2f,
    [KnownColor.DarkOrange]: 0xffff8c00,
    [KnownColor.DarkOrchid]: 0xff9932cc,
    [KnownColor.DarkRed]: 0xff8b0000,
    [KnownColor.DarkSalmon]: 0xffe9967a,
    [KnownColor.DarkSeaGreen]: 0xff8fbc8f,
    [KnownColor.DarkSlateBlue]: 0xff483d8b,
    [KnownColor.DarkSlateGray]: 0xff2f4f4f,
    [KnownColor.DarkTurquoise]: 0xff00ced1,
    [KnownColor.DarkViolet]: 0xff9400d3,
    [KnownColor.DeepPink]: 0xffff1493,
    [KnownColor.DeepSkyBlue]: 0xff00bfff,
    [KnownColor.DimGray]: 0xff696969,
    [KnownColor.DodgerBlue]: 0xff1e90ff,
    [KnownColor.Firebrick]: 0xffb22222,
    [KnownColor.FloralWhite]: 0xfffffaf0,
    [KnownColor.ForestGreen]: 0xff228b22,
    [KnownColor.Fuchsia]: 0xffff00ff,
    [KnownColor.Gainsboro]: 0xffdcdcdc,
    [KnownColor.GhostWhite]: 0xfff8f8ff,
    [KnownColor.Gold]: 0xffffd700,
    [KnownColor.Goldenrod]: 0xffdaa520,
    [KnownColor.Gray]: 0xff808080,
    [KnownColor.Green]: 0xff008000,
    [KnownColor.GreenYellow]: 0xffadff2f,
    [KnownColor.Honeydew]: 0xfff0fff0,
    [KnownColor.HotPink]: 0xffff69b4,
    [KnownColor.IndianRed]: 0xffcd5c5c,
    [KnownColor.Indigo]: 0xff4b0082,
    [KnownColor.Ivory]: 0xfffffff0,
    [KnownColor.Khaki]: 0xfff0e68c,
    [KnownColor.Lavender]: 0xffe6e6fa,
    [KnownColor.LavenderBlush]: 0xfffff0f5,
    [KnownColor.LawnGreen]: 0xff7cfc00,
    [KnownColor.LemonChiffon]: 0xfffffacd,
    [KnownColor.LightBlue]: 0xffadd8e6,
    [KnownColor.LightCoral]: 0xfff08080,
    [KnownColor.LightCyan]: 0xffe0ffff,
    [KnownColor.LightGoldenrodYellow]: 0xfffafad2,
    [KnownColor.LightGray]: 0xffd3d3d3,
    [KnownColor.LightGreen]: 0xff90ee90,
    [KnownColor.LightPink]: 0xffffb6c1,
    [KnownColor.LightSalmon]: 0xffffa07a,
    [KnownColor.LightSeaGreen]: 0xff20b2aa,
    [KnownColor.LightSkyBlue]: 0xff87cefa,
    [KnownColor.LightSlateGray]: 0xff778899,
    [KnownColor.LightSteelBlue]: 0xffb0c4de,
    [KnownColor.LightYellow]: 0xffffffe0,
    [KnownColor.Lime]: 0xff00ff00,
    [KnownColor.LimeGreen]: 0xff32cd32,
    [KnownColor.Linen]: 0xfffaf0e6,
    [KnownColor.Magenta]: 0xffff00ff,
    [KnownColor.Maroon]: 0xff800000,
    [KnownColor.MediumAquamarine]: 0xff66cdaa,
    [KnownColor.MediumBlue]: 0xff0000cd,
    [KnownColor.MediumOrchid]: 0xffba55d3,
    [KnownColor.MediumPurple]: 0xff9370db,
    [KnownColor.MediumSeaGreen]: 0xff3cb371,
    [KnownColor.MediumSlateBlue]: 0xff7b68ee,
    [KnownColor.MediumSpringGreen]: 0xff00fa9a,
    [KnownColor.MediumTurquoise]: 0xff48d1cc,
    [KnownColor.MediumVioletRed]: 0xffc71585,
    [KnownColor.MidnightBlue]: 0xff191970,
    [KnownColor.MintCream]: 0xfff5fffa,
    [KnownColor.MistyRose]: 0xffffe4e1,
    [KnownColor.Moccasin]: 0xffffe4b5,
    [KnownColor.NavajoWhite]: 0xffffdead,
    [KnownColor.Navy]: 0xff000080,
    [KnownColor.OldLace]: 0xfffdf5e6,
    [KnownColor.Olive]: 0xff808000,
    [KnownColor.OliveDrab]: 0xff6b8e23,
    [KnownColor.Orange]: 0xffffa500,
    [KnownColor.OrangeRed]: 0xffff4500,
    [KnownColor.Orchid]: 0xffda70d6,
    [KnownColor.PaleGoldenrod]: 0xffeee8aa,
    [KnownColor.PaleGreen]: 0xff98fb98,
    [KnownColor.PaleTurquoise]: 0xffafeeee,
    [KnownColor.PaleVioletRed]: 0xffdb7093,
    [KnownColor.PapayaWhip]: 0xffffefd5,
    [KnownColor.PeachPuff]: 0xffffdab9,
    [KnownColor.Peru]: 0xffcd853f,
    [KnownColor.Pink]: 0xffffc0cb,
    [KnownColor.Plum]: 0xffdda0dd,
    [KnownColor.PowderBlue]: 0xffb0e0e6,
    [KnownColor.Purple]: 0xff800080,
    [KnownColor.Red]: 0xffff0000,
    [KnownColor.RosyBrown]: 0xffbc8f8f,
    [KnownColor.RoyalBlue]: 0xff4169e1,
    [KnownColor.SaddleBrown]: 0xff8b4513,
    [KnownColor.Salmon]: 0xfffa8072,
    [KnownColor.SandyBrown]: 0xfff4a460,
    [KnownColor.SeaGreen]: 0xff2e8b57,
    [KnownColor.SeaShell]: 0xfffff5ee,
    [KnownColor.Sienna]: 0xffa0522d,
    [KnownColor.Silver]: 0xffc0c0c0,
    [KnownColor.SkyBlue]: 0xff87ceeb,
    [KnownColor.SlateBlue]: 0xff6a5acd,
    [KnownColor.SlateGray]: 0xff708090,
    [KnownColor.Snow]: 0xfffffafa,
    [KnownColor.SpringGreen]: 0xff00ff7f,
    [KnownColor.SteelBlue]: 0xff4682b4,
    [KnownColor.Tan]: 0xffd2b48c,
    [KnownColor.Teal]: 0xff008080,
    [KnownColor.Thistle]: 0xffd8bfd8,
    [KnownColor.Tomato]: 0xffff6347,
    [KnownColor.Turquoise]: 0xff40e0d0,
    [KnownColor.Violet]: 0xffee82ee,
    [KnownColor.Wheat]: 0xfff5deb3,
    [KnownColor.White]: 0xffffffff,
    [KnownColor.WhiteSmoke]: 0xfff5f5f5,
    [KnownColor.Yellow]: 0xffffff00,
    [KnownColor.YellowGreen]: 0xff9acd32,
    [KnownColor.RebeccaPurple]: 0xff663399,
};

export function known_color_to_argb(color: KnownColor): number {
    return COLOR_VALUE_TABLE[color] ?? 0;
}

export function argb_to_known_color(argb: number): KnownColor | null {
    const masked_argb = argb | 0xff000000;
    for (const [key, value] of Object.entries(COLOR_VALUE_TABLE)) {
        if (value === masked_argb) {
            return parseInt(key) as KnownColor;
        }
    }
    return null;
}
